name: Python Linting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Python Style Checker
      uses: andymckay/pycodestyle-action@0.1.3
